name: tsukuyomi_list
description: List views for Tsukuyomi.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: any
  vector_math: any
  sliver_tools: any
  collection: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
