name: tsukuyomi_html
description: Html parser for Tsukuyomi.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.7 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 源代码位置信息
  source_span: 1.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
