name: tsukuyomi_metadata
description: Platform metadata for Tsukuyomi.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.7 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 插件平台接口
  plugin_platform_interface: 2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.flop.tsukuyomi_metadata
        pluginClass: TsukuyomiMetadataPlugin
