name: tsukuyomi_metadata
description: Platform metadata for Tsukuyomi.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=3.10.0-290.4.beta <4.0.0"
  flutter: ">=3.38.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 插件平台接口
  plugin_platform_interface: 2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.flop.tsukuyomi_metadata
        pluginClass: TsukuyomiMetadataPlugin
